"""Puntos de monitoreo curados: ~150 ubicaciones (60% LatAm, 40% resto del mundo).

Fuente de verdad para los 3 extractores Open-Meteo (1-3 llamadas multicoordenada).
Campos: id, ciudad, pais, iso3, region, lat, lon, tipo (ciudad/cuenca).
"""
from __future__ import annotations

PUNTOS = [
    # ---- LATAM (~90): México y Centroamérica ----
    {"id": "cdmx-mx", "ciudad": "Ciudad de México", "pais": "México", "iso3": "MEX", "region": "LatAm", "lat": 19.43, "lon": -99.13, "tipo": "ciudad"},
    {"id": "guadalajara-mx", "ciudad": "Guadalajara", "pais": "México", "iso3": "MEX", "region": "LatAm", "lat": 20.67, "lon": -103.35, "tipo": "ciudad"},
    {"id": "monterrey-mx", "ciudad": "Monterrey", "pais": "México", "iso3": "MEX", "region": "LatAm", "lat": 25.67, "lon": -100.31, "tipo": "ciudad"},
    {"id": "puebla-mx", "ciudad": "Puebla", "pais": "México", "iso3": "MEX", "region": "LatAm", "lat": 19.04, "lon": -98.20, "tipo": "ciudad"},
    {"id": "tijuana-mx", "ciudad": "Tijuana", "pais": "México", "iso3": "MEX", "region": "LatAm", "lat": 32.51, "lon": -117.03, "tipo": "ciudad"},
    {"id": "cancun-mx", "ciudad": "Cancún", "pais": "México", "iso3": "MEX", "region": "LatAm", "lat": 21.16, "lon": -86.85, "tipo": "ciudad"},
    {"id": "oaxaca-mx", "ciudad": "Oaxaca", "pais": "México", "iso3": "MEX", "region": "LatAm", "lat": 17.07, "lon": -96.72, "tipo": "ciudad"},
    {"id": "guatemala-gt", "ciudad": "Ciudad de Guatemala", "pais": "Guatemala", "iso3": "GTM", "region": "LatAm", "lat": 14.63, "lon": -90.55, "tipo": "ciudad"},
    {"id": "quetzaltenango-gt", "ciudad": "Quetzaltenango", "pais": "Guatemala", "iso3": "GTM", "region": "LatAm", "lat": 14.83, "lon": -91.52, "tipo": "ciudad"},
    {"id": "belmopan-bz", "ciudad": "Belmopán", "pais": "Belice", "iso3": "BLZ", "region": "LatAm", "lat": 17.25, "lon": -88.77, "tipo": "ciudad"},
    {"id": "tegucigalpa-hn", "ciudad": "Tegucigalpa", "pais": "Honduras", "iso3": "HND", "region": "LatAm", "lat": 14.08, "lon": -87.20, "tipo": "ciudad"},
    {"id": "san-pedro-sula-hn", "ciudad": "San Pedro Sula", "pais": "Honduras", "iso3": "HND", "region": "LatAm", "lat": 15.50, "lon": -88.03, "tipo": "ciudad"},
    {"id": "san-salvador-sv", "ciudad": "San Salvador", "pais": "El Salvador", "iso3": "SLV", "region": "LatAm", "lat": 13.69, "lon": -89.19, "tipo": "ciudad"},
    {"id": "managua-ni", "ciudad": "Managua", "pais": "Nicaragua", "iso3": "NIC", "region": "LatAm", "lat": 12.13, "lon": -86.27, "tipo": "ciudad"},
    {"id": "bluefields-ni", "ciudad": "Bluefields", "pais": "Nicaragua", "iso3": "NIC", "region": "LatAm", "lat": 12.01, "lon": -83.76, "tipo": "ciudad"},
    {"id": "san-jose-cr", "ciudad": "San José", "pais": "Costa Rica", "iso3": "CRI", "region": "LatAm", "lat": 9.93, "lon": -84.09, "tipo": "ciudad"},
    {"id": "limon-cr", "ciudad": "Limón", "pais": "Costa Rica", "iso3": "CRI", "region": "LatAm", "lat": 9.99, "lon": -83.03, "tipo": "ciudad"},
    {"id": "panama-pa", "ciudad": "Ciudad de Panamá", "pais": "Panamá", "iso3": "PAN", "region": "LatAm", "lat": 8.98, "lon": -79.52, "tipo": "ciudad"},
    {"id": "colon-pa", "ciudad": "Colón", "pais": "Panamá", "iso3": "PAN", "region": "LatAm", "lat": 9.35, "lon": -79.90, "tipo": "ciudad"},
    # ---- Caribe ----
    {"id": "habana-cu", "ciudad": "La Habana", "pais": "Cuba", "iso3": "CUB", "region": "LatAm", "lat": 23.14, "lon": -82.37, "tipo": "ciudad"},
    {"id": "santiago-cu", "ciudad": "Santiago de Cuba", "pais": "Cuba", "iso3": "CUB", "region": "LatAm", "lat": 20.02, "lon": -75.83, "tipo": "ciudad"},
    {"id": "kingston-jm", "ciudad": "Kingston", "pais": "Jamaica", "iso3": "JAM", "region": "LatAm", "lat": 18.01, "lon": -76.80, "tipo": "ciudad"},
    {"id": "puerto-principe-ht", "ciudad": "Puerto Príncipe", "pais": "Haití", "iso3": "HTI", "region": "LatAm", "lat": 18.54, "lon": -72.34, "tipo": "ciudad"},
    {"id": "santo-domingo-do", "ciudad": "Santo Domingo", "pais": "Rep. Dominicana", "iso3": "DOM", "region": "LatAm", "lat": 18.49, "lon": -69.93, "tipo": "ciudad"},
    {"id": "santiago-do", "ciudad": "Santiago de los Caballeros", "pais": "Rep. Dominicana", "iso3": "DOM", "region": "LatAm", "lat": 19.45, "lon": -70.70, "tipo": "ciudad"},
    {"id": "san-juan-pr", "ciudad": "San Juan", "pais": "Puerto Rico", "iso3": "PRI", "region": "LatAm", "lat": 18.46, "lon": -66.11, "tipo": "ciudad"},
    {"id": "puerto-espana-tt", "ciudad": "Puerto España", "pais": "Trinidad y Tobago", "iso3": "TTO", "region": "LatAm", "lat": 10.65, "lon": -61.52, "tipo": "ciudad"},
    # ---- Sudamérica andina ----
    {"id": "bogota-co", "ciudad": "Bogotá", "pais": "Colombia", "iso3": "COL", "region": "LatAm", "lat": 4.71, "lon": -74.07, "tipo": "ciudad"},
    {"id": "medellin-co", "ciudad": "Medellín", "pais": "Colombia", "iso3": "COL", "region": "LatAm", "lat": 6.24, "lon": -75.57, "tipo": "ciudad"},
    {"id": "cali-co", "ciudad": "Cali", "pais": "Colombia", "iso3": "COL", "region": "LatAm", "lat": 3.42, "lon": -76.52, "tipo": "ciudad"},
    {"id": "barranquilla-co", "ciudad": "Barranquilla", "pais": "Colombia", "iso3": "COL", "region": "LatAm", "lat": 10.96, "lon": -74.80, "tipo": "ciudad"},
    {"id": "cartagena-co", "ciudad": "Cartagena", "pais": "Colombia", "iso3": "COL", "region": "LatAm", "lat": 10.39, "lon": -75.51, "tipo": "ciudad"},
    {"id": "leticia-co", "ciudad": "Leticia", "pais": "Colombia", "iso3": "COL", "region": "LatAm", "lat": -4.21, "lon": -69.94, "tipo": "cuenca"},
    {"id": "caracas-ve", "ciudad": "Caracas", "pais": "Venezuela", "iso3": "VEN", "region": "LatAm", "lat": 10.48, "lon": -66.90, "tipo": "ciudad"},
    {"id": "maracaibo-ve", "ciudad": "Maracaibo", "pais": "Venezuela", "iso3": "VEN", "region": "LatAm", "lat": 10.65, "lon": -71.65, "tipo": "ciudad"},
    {"id": "guayana-ve", "ciudad": "Ciudad Guayana", "pais": "Venezuela", "iso3": "VEN", "region": "LatAm", "lat": 8.37, "lon": -62.64, "tipo": "cuenca"},
    {"id": "quito-ec", "ciudad": "Quito", "pais": "Ecuador", "iso3": "ECU", "region": "LatAm", "lat": -0.18, "lon": -78.47, "tipo": "ciudad"},
    {"id": "guayaquil-ec", "ciudad": "Guayaquil", "pais": "Ecuador", "iso3": "ECU", "region": "LatAm", "lat": -2.19, "lon": -79.89, "tipo": "ciudad"},
    {"id": "cuenca-ec", "ciudad": "Cuenca", "pais": "Ecuador", "iso3": "ECU", "region": "LatAm", "lat": -2.90, "lon": -79.00, "tipo": "ciudad"},
    {"id": "galapagos-ec", "ciudad": "Puerto Ayora (Galápagos)", "pais": "Ecuador", "iso3": "ECU", "region": "LatAm", "lat": -0.74, "lon": -90.31, "tipo": "ciudad"},
    {"id": "lima-pe", "ciudad": "Lima", "pais": "Perú", "iso3": "PER", "region": "LatAm", "lat": -12.04, "lon": -77.04, "tipo": "ciudad"},
    {"id": "arequipa-pe", "ciudad": "Arequipa", "pais": "Perú", "iso3": "PER", "region": "LatAm", "lat": -16.40, "lon": -71.53, "tipo": "ciudad"},
    {"id": "cusco-pe", "ciudad": "Cusco", "pais": "Perú", "iso3": "PER", "region": "LatAm", "lat": -13.53, "lon": -71.97, "tipo": "ciudad"},
    {"id": "iquitos-pe", "ciudad": "Iquitos", "pais": "Perú", "iso3": "PER", "region": "LatAm", "lat": -3.75, "lon": -73.25, "tipo": "cuenca"},
    {"id": "piura-pe", "ciudad": "Piura", "pais": "Perú", "iso3": "PER", "region": "LatAm", "lat": -5.19, "lon": -80.63, "tipo": "ciudad"},
    {"id": "lapaz-bo", "ciudad": "La Paz", "pais": "Bolivia", "iso3": "BOL", "region": "LatAm", "lat": -16.49, "lon": -68.12, "tipo": "ciudad"},
    {"id": "santacruz-bo", "ciudad": "Santa Cruz", "pais": "Bolivia", "iso3": "BOL", "region": "LatAm", "lat": -17.78, "lon": -63.18, "tipo": "ciudad"},
    {"id": "cochabamba-bo", "ciudad": "Cochabamba", "pais": "Bolivia", "iso3": "BOL", "region": "LatAm", "lat": -17.39, "lon": -66.16, "tipo": "ciudad"},
    {"id": "uyuni-bo", "ciudad": "Uyuni", "pais": "Bolivia", "iso3": "BOL", "region": "LatAm", "lat": -20.46, "lon": -66.83, "tipo": "ciudad"},
    # ---- Cono Sur ----
    {"id": "santiago-cl", "ciudad": "Santiago", "pais": "Chile", "iso3": "CHL", "region": "LatAm", "lat": -33.45, "lon": -70.66, "tipo": "ciudad"},
    {"id": "valparaiso-cl", "ciudad": "Valparaíso", "pais": "Chile", "iso3": "CHL", "region": "LatAm", "lat": -33.04, "lon": -71.63, "tipo": "ciudad"},
    {"id": "antofagasta-cl", "ciudad": "Antofagasta", "pais": "Chile", "iso3": "CHL", "region": "LatAm", "lat": -23.65, "lon": -70.40, "tipo": "ciudad"},
    {"id": "punta-arenas-cl", "ciudad": "Punta Arenas", "pais": "Chile", "iso3": "CHL", "region": "LatAm", "lat": -53.16, "lon": -70.91, "tipo": "ciudad"},
    {"id": "pascua-cl", "ciudad": "Hanga Roa (Rapa Nui)", "pais": "Chile", "iso3": "CHL", "region": "LatAm", "lat": -27.11, "lon": -109.35, "tipo": "ciudad"},
    {"id": "buenos-aires-ar", "ciudad": "Buenos Aires", "pais": "Argentina", "iso3": "ARG", "region": "LatAm", "lat": -34.60, "lon": -58.38, "tipo": "ciudad"},
    {"id": "cordoba-ar", "ciudad": "Córdoba", "pais": "Argentina", "iso3": "ARG", "region": "LatAm", "lat": -31.42, "lon": -64.18, "tipo": "ciudad"},
    {"id": "mendoza-ar", "ciudad": "Mendoza", "pais": "Argentina", "iso3": "ARG", "region": "LatAm", "lat": -32.89, "lon": -68.84, "tipo": "ciudad"},
    {"id": "ushuaia-ar", "ciudad": "Ushuaia", "pais": "Argentina", "iso3": "ARG", "region": "LatAm", "lat": -54.80, "lon": -68.30, "tipo": "ciudad"},
    {"id": "bariloche-ar", "ciudad": "Bariloche", "pais": "Argentina", "iso3": "ARG", "region": "LatAm", "lat": -41.13, "lon": -71.31, "tipo": "ciudad"},
    {"id": "salta-ar", "ciudad": "Salta", "pais": "Argentina", "iso3": "ARG", "region": "LatAm", "lat": -24.78, "lon": -65.41, "tipo": "ciudad"},
    {"id": "montevideo-uy", "ciudad": "Montevideo", "pais": "Uruguay", "iso3": "URY", "region": "LatAm", "lat": -34.90, "lon": -56.16, "tipo": "ciudad"},
    {"id": "salto-uy", "ciudad": "Salto", "pais": "Uruguay", "iso3": "URY", "region": "LatAm", "lat": -31.38, "lon": -57.96, "tipo": "ciudad"},
    {"id": "asuncion-py", "ciudad": "Asunción", "pais": "Paraguay", "iso3": "PRY", "region": "LatAm", "lat": -25.26, "lon": -57.58, "tipo": "ciudad"},
    {"id": "cde-py", "ciudad": "Ciudad del Este", "pais": "Paraguay", "iso3": "PRY", "region": "LatAm", "lat": -25.51, "lon": -54.61, "tipo": "ciudad"},
    # ---- Brasil + Guayanas ----
    {"id": "sao-paulo-br", "ciudad": "São Paulo", "pais": "Brasil", "iso3": "BRA", "region": "LatAm", "lat": -23.55, "lon": -46.63, "tipo": "ciudad"},
    {"id": "rio-br", "ciudad": "Río de Janeiro", "pais": "Brasil", "iso3": "BRA", "region": "LatAm", "lat": -22.91, "lon": -43.17, "tipo": "ciudad"},
    {"id": "brasilia-br", "ciudad": "Brasilia", "pais": "Brasil", "iso3": "BRA", "region": "LatAm", "lat": -15.79, "lon": -47.88, "tipo": "ciudad"},
    {"id": "manaus-br", "ciudad": "Manaos", "pais": "Brasil", "iso3": "BRA", "region": "LatAm", "lat": -3.11, "lon": -60.02, "tipo": "cuenca"},
    {"id": "belem-br", "ciudad": "Belém", "pais": "Brasil", "iso3": "BRA", "region": "LatAm", "lat": -1.45, "lon": -48.49, "tipo": "cuenca"},
    {"id": "recife-br", "ciudad": "Recife", "pais": "Brasil", "iso3": "BRA", "region": "LatAm", "lat": -8.05, "lon": -34.90, "tipo": "ciudad"},
    {"id": "salvador-br", "ciudad": "Salvador", "pais": "Brasil", "iso3": "BRA", "region": "LatAm", "lat": -12.97, "lon": -38.50, "tipo": "ciudad"},
    {"id": "porto-alegre-br", "ciudad": "Porto Alegre", "pais": "Brasil", "iso3": "BRA", "region": "LatAm", "lat": -30.03, "lon": -51.23, "tipo": "ciudad"},
    {"id": "cuiaba-br", "ciudad": "Cuiabá", "pais": "Brasil", "iso3": "BRA", "region": "LatAm", "lat": -15.60, "lon": -56.09, "tipo": "ciudad"},
    {"id": "fortaleza-br", "ciudad": "Fortaleza", "pais": "Brasil", "iso3": "BRA", "region": "LatAm", "lat": -3.73, "lon": -38.52, "tipo": "ciudad"},
    {"id": "georgetown-gy", "ciudad": "Georgetown", "pais": "Guyana", "iso3": "GUY", "region": "LatAm", "lat": 6.80, "lon": -58.16, "tipo": "ciudad"},
    {"id": "paramaribo-sr", "ciudad": "Paramaribo", "pais": "Surinam", "iso3": "SUR", "region": "LatAm", "lat": 5.85, "lon": -55.20, "tipo": "ciudad"},
    {"id": "cayena-gf", "ciudad": "Cayena", "pais": "Guayana Francesa", "iso3": "GUF", "region": "LatAm", "lat": 4.93, "lon": -52.32, "tipo": "ciudad"},
    {"id": "pasto-co", "ciudad": "Pasto", "pais": "Colombia", "iso3": "COL", "region": "LatAm", "lat": 1.21, "lon": -77.28, "tipo": "ciudad"},
    {"id": "puno-pe", "ciudad": "Puno", "pais": "Perú", "iso3": "PER", "region": "LatAm", "lat": -15.84, "lon": -70.02, "tipo": "ciudad"},
    {"id": "valledupar-co", "ciudad": "Valledupar", "pais": "Colombia", "iso3": "COL", "region": "LatAm", "lat": 10.47, "lon": -73.25, "tipo": "ciudad"},
    {"id": "santa-marta-co", "ciudad": "Santa Marta", "pais": "Colombia", "iso3": "COL", "region": "LatAm", "lat": 11.24, "lon": -74.21, "tipo": "ciudad"},
    {"id": "villavicencio-co", "ciudad": "Villavicencio", "pais": "Colombia", "iso3": "COL", "region": "LatAm", "lat": 4.15, "lon": -73.63, "tipo": "ciudad"},
    {"id": "tuxtla-mx", "ciudad": "Tuxtla Gutiérrez", "pais": "México", "iso3": "MEX", "region": "LatAm", "lat": 16.75, "lon": -93.11, "tipo": "ciudad"},
    {"id": "merida-mx", "ciudad": "Mérida", "pais": "México", "iso3": "MEX", "region": "LatAm", "lat": 20.97, "lon": -89.62, "tipo": "ciudad"},
    {"id": "quito-rural-ec", "ciudad": "Tena (Amazonía)", "pais": "Ecuador", "iso3": "ECU", "region": "LatAm", "lat": -0.99, "lon": -77.81, "tipo": "cuenca"},
    {"id": "cobija-bo", "ciudad": "Cobija", "pais": "Bolivia", "iso3": "BOL", "region": "LatAm", "lat": -11.03, "lon": -68.74, "tipo": "cuenca"},
    {"id": "rosario-ar", "ciudad": "Rosario", "pais": "Argentina", "iso3": "ARG", "region": "LatAm", "lat": -32.95, "lon": -60.65, "tipo": "ciudad"},
    # ---- RESTO DEL MUNDO (~60) ----
    {"id": "madrid-es", "ciudad": "Madrid", "pais": "España", "iso3": "ESP", "region": "Mundo", "lat": 40.42, "lon": -3.70, "tipo": "ciudad"},
    {"id": "barcelona-es", "ciudad": "Barcelona", "pais": "España", "iso3": "ESP", "region": "Mundo", "lat": 41.39, "lon": 2.17, "tipo": "ciudad"},
    {"id": "lisboa-pt", "ciudad": "Lisboa", "pais": "Portugal", "iso3": "PRT", "region": "Mundo", "lat": 38.72, "lon": -9.14, "tipo": "ciudad"},
    {"id": "paris-fr", "ciudad": "París", "pais": "Francia", "iso3": "FRA", "region": "Mundo", "lat": 48.85, "lon": 2.35, "tipo": "ciudad"},
    {"id": "londres-gb", "ciudad": "Londres", "pais": "Reino Unido", "iso3": "GBR", "region": "Mundo", "lat": 51.50, "lon": -0.13, "tipo": "ciudad"},
    {"id": "berlin-de", "ciudad": "Berlín", "pais": "Alemania", "iso3": "DEU", "region": "Mundo", "lat": 52.52, "lon": 13.40, "tipo": "ciudad"},
    {"id": "roma-it", "ciudad": "Roma", "pais": "Italia", "iso3": "ITA", "region": "Mundo", "lat": 41.90, "lon": 12.50, "tipo": "ciudad"},
    {"id": "amsterdam-nl", "ciudad": "Ámsterdam", "pais": "Países Bajos", "iso3": "NLD", "region": "Mundo", "lat": 52.37, "lon": 4.90, "tipo": "ciudad"},
    {"id": "bruselas-be", "ciudad": "Bruselas", "pais": "Bélgica", "iso3": "BEL", "region": "Mundo", "lat": 50.85, "lon": 4.35, "tipo": "ciudad"},
    {"id": "varsovia-pl", "ciudad": "Varsovia", "pais": "Polonia", "iso3": "POL", "region": "Mundo", "lat": 52.23, "lon": 21.01, "tipo": "ciudad"},
    {"id": "atenas-gr", "ciudad": "Atenas", "pais": "Grecia", "iso3": "GRC", "region": "Mundo", "lat": 37.98, "lon": 23.73, "tipo": "ciudad"},
    {"id": "estambul-tr", "ciudad": "Estambul", "pais": "Turquía", "iso3": "TUR", "region": "Mundo", "lat": 41.01, "lon": 28.98, "tipo": "ciudad"},
    {"id": "moscu-ru", "ciudad": "Moscú", "pais": "Rusia", "iso3": "RUS", "region": "Mundo", "lat": 55.76, "lon": 37.62, "tipo": "ciudad"},
    {"id": "kiev-ua", "ciudad": "Kiev", "pais": "Ucrania", "iso3": "UKR", "region": "Mundo", "lat": 50.45, "lon": 30.52, "tipo": "ciudad"},
    {"id": "el-cairo-eg", "ciudad": "El Cairo", "pais": "Egipto", "iso3": "EGY", "region": "Mundo", "lat": 30.04, "lon": 31.24, "tipo": "ciudad"},
    {"id": "lagos-ng", "ciudad": "Lagos", "pais": "Nigeria", "iso3": "NGA", "region": "Mundo", "lat": 6.52, "lon": 3.38, "tipo": "ciudad"},
    {"id": "dakar-sn", "ciudad": "Dakar", "pais": "Senegal", "iso3": "SEN", "region": "Mundo", "lat": 14.69, "lon": -17.44, "tipo": "ciudad"},
    {"id": "kinshasa-cd", "ciudad": "Kinsasa", "pais": "R.D. Congo", "iso3": "COD", "region": "Mundo", "lat": -4.32, "lon": 15.31, "tipo": "ciudad"},
    {"id": "nairobi-ke", "ciudad": "Nairobi", "pais": "Kenia", "iso3": "KEN", "region": "Mundo", "lat": -1.29, "lon": 36.82, "tipo": "ciudad"},
    {"id": "addis-et", "ciudad": "Adís Abeba", "pais": "Etiopía", "iso3": "ETH", "region": "Mundo", "lat": 9.01, "lon": 38.75, "tipo": "ciudad"},
    {"id": "johannesburgo-za", "ciudad": "Johannesburgo", "pais": "Sudáfrica", "iso3": "ZAF", "region": "Mundo", "lat": -26.20, "lon": 28.05, "tipo": "ciudad"},
    {"id": "ciudad-cabo-za", "ciudad": "Ciudad del Cabo", "pais": "Sudáfrica", "iso3": "ZAF", "region": "Mundo", "lat": -33.92, "lon": 18.42, "tipo": "ciudad"},
    {"id": "nueva-delhi-in", "ciudad": "Nueva Delhi", "pais": "India", "iso3": "IND", "region": "Mundo", "lat": 28.61, "lon": 77.21, "tipo": "ciudad"},
    {"id": "mumbai-in", "ciudad": "Mumbai", "pais": "India", "iso3": "IND", "region": "Mundo", "lat": 19.08, "lon": 72.88, "tipo": "ciudad"},
    {"id": "calcuta-in", "ciudad": "Calcuta", "pais": "India", "iso3": "IND", "region": "Mundo", "lat": 22.57, "lon": 88.36, "tipo": "ciudad"},
    {"id": "dhaka-bd", "ciudad": "Daca", "pais": "Bangladés", "iso3": "BGD", "region": "Mundo", "lat": 23.81, "lon": 90.41, "tipo": "ciudad"},
    {"id": "yakarta-id", "ciudad": "Yakarta", "pais": "Indonesia", "iso3": "IDN", "region": "Mundo", "lat": -6.21, "lon": 106.85, "tipo": "ciudad"},
    {"id": "manila-ph", "ciudad": "Manila", "pais": "Filipinas", "iso3": "PHL", "region": "Mundo", "lat": 14.60, "lon": 120.98, "tipo": "ciudad"},
    {"id": "bangkok-th", "ciudad": "Bangkok", "pais": "Tailandia", "iso3": "THA", "region": "Mundo", "lat": 13.76, "lon": 100.50, "tipo": "ciudad"},
    {"id": "hanoi-vn", "ciudad": "Hanói", "pais": "Vietnam", "iso3": "VNM", "region": "Mundo", "lat": 21.03, "lon": 105.85, "tipo": "ciudad"},
    {"id": "pekin-cn", "ciudad": "Pekín", "pais": "China", "iso3": "CHN", "region": "Mundo", "lat": 39.90, "lon": 116.40, "tipo": "ciudad"},
    {"id": "shanghai-cn", "ciudad": "Shanghái", "pais": "China", "iso3": "CHN", "region": "Mundo", "lat": 31.23, "lon": 121.47, "tipo": "ciudad"},
    {"id": "seul-kr", "ciudad": "Seúl", "pais": "Corea del Sur", "iso3": "KOR", "region": "Mundo", "lat": 37.57, "lon": 126.98, "tipo": "ciudad"},
    {"id": "tokio-jp", "ciudad": "Tokio", "pais": "Japón", "iso3": "JPN", "region": "Mundo", "lat": 35.69, "lon": 139.69, "tipo": "ciudad"},
    {"id": "osaka-jp", "ciudad": "Osaka", "pais": "Japón", "iso3": "JPN", "region": "Mundo", "lat": 34.69, "lon": 135.50, "tipo": "ciudad"},
    {"id": "sidney-au", "ciudad": "Sídney", "pais": "Australia", "iso3": "AUS", "region": "Mundo", "lat": -33.87, "lon": 151.21, "tipo": "ciudad"},
    {"id": "melbourne-au", "ciudad": "Melbourne", "pais": "Australia", "iso3": "AUS", "region": "Mundo", "lat": -37.81, "lon": 144.96, "tipo": "ciudad"},
    {"id": "auckland-nz", "ciudad": "Auckland", "pais": "Nueva Zelanda", "iso3": "NZL", "region": "Mundo", "lat": -36.85, "lon": 174.76, "tipo": "ciudad"},
    {"id": "nueva-york-us", "ciudad": "Nueva York", "pais": "EE. UU.", "iso3": "USA", "region": "Mundo", "lat": 40.71, "lon": -74.01, "tipo": "ciudad"},
    {"id": "los-angeles-us", "ciudad": "Los Ángeles", "pais": "EE. UU.", "iso3": "USA", "region": "Mundo", "lat": 34.05, "lon": -118.24, "tipo": "ciudad"},
    {"id": "chicago-us", "ciudad": "Chicago", "pais": "EE. UU.", "iso3": "USA", "region": "Mundo", "lat": 41.88, "lon": -87.63, "tipo": "ciudad"},
    {"id": "houston-us", "ciudad": "Houston", "pais": "EE. UU.", "iso3": "USA", "region": "Mundo", "lat": 29.76, "lon": -95.37, "tipo": "ciudad"},
    {"id": "san-francisco-us", "ciudad": "San Francisco", "pais": "EE. UU.", "iso3": "USA", "region": "Mundo", "lat": 37.77, "lon": -122.42, "tipo": "ciudad"},
    {"id": "toronto-ca", "ciudad": "Toronto", "pais": "Canadá", "iso3": "CAN", "region": "Mundo", "lat": 43.65, "lon": -79.38, "tipo": "ciudad"},
    {"id": "vancouver-ca", "ciudad": "Vancouver", "pais": "Canadá", "iso3": "CAN", "region": "Mundo", "lat": 49.28, "lon": -123.12, "tipo": "ciudad"},
    {"id": "teheran-ir", "ciudad": "Teherán", "pais": "Irán", "iso3": "IRN", "region": "Mundo", "lat": 35.69, "lon": 51.39, "tipo": "ciudad"},
    {"id": "bagdad-iq", "ciudad": "Bagdad", "pais": "Irak", "iso3": "IRQ", "region": "Mundo", "lat": 33.31, "lon": 44.36, "tipo": "ciudad"},
    {"id": "riad-sa", "ciudad": "Riad", "pais": "Arabia Saudita", "iso3": "SAU", "region": "Mundo", "lat": 24.71, "lon": 46.68, "tipo": "ciudad"},
    {"id": "tel-aviv-il", "ciudad": "Tel Aviv", "pais": "Israel", "iso3": "ISR", "region": "Mundo", "lat": 32.08, "lon": 34.78, "tipo": "ciudad"},
    {"id": "moscu-cuenca-ru", "ciudad": "Volgogrado (Volga)", "pais": "Rusia", "iso3": "RUS", "region": "Mundo", "lat": 48.71, "lon": 44.51, "tipo": "cuenca"},
    {"id": "el-cairo-nilo-eg", "ciudad": "Asuán (Nilo)", "pais": "Egipto", "iso3": "EGY", "region": "Mundo", "lat": 24.09, "lon": 32.90, "tipo": "cuenca"},
    {"id": "amazonas-br", "ciudad": "Santarém (Amazonas)", "pais": "Brasil", "iso3": "BRA", "region": "LatAm", "lat": -2.44, "lon": -54.70, "tipo": "cuenca"},
    {"id": "parana-ar", "ciudad": "Paraná (río Paraná)", "pais": "Argentina", "iso3": "ARG", "region": "LatAm", "lat": -31.73, "lon": -60.53, "tipo": "cuenca"},
    {"id": "danubio-hu", "ciudad": "Budapest (Danubio)", "pais": "Hungría", "iso3": "HUN", "region": "Mundo", "lat": 47.50, "lon": 19.04, "tipo": "cuenca"},
    {"id": "mekong-vn", "ciudad": "Can Tho (Mekong)", "pais": "Vietnam", "iso3": "VNM", "region": "Mundo", "lat": 10.04, "lon": 105.77, "tipo": "cuenca"},
    {"id": "ganges-in", "ciudad": "Varanasi (Ganges)", "pais": "India", "iso3": "IND", "region": "Mundo", "lat": 25.32, "lon": 82.99, "tipo": "cuenca"},
    {"id": "mississippi-us", "ciudad": "Nueva Orleans (Misisipi)", "pais": "EE. UU.", "iso3": "USA", "region": "Mundo", "lat": 29.95, "lon": -90.07, "tipo": "cuenca"},
    {"id": "nilo-sd", "ciudad": "Jartum (Nilo)", "pais": "Sudán", "iso3": "SDN", "region": "Mundo", "lat": 15.50, "lon": 32.56, "tipo": "cuenca"},
    {"id": "yangtze-cn", "ciudad": "Wuhan (Yangtsé)", "pais": "China", "iso3": "CHN", "region": "Mundo", "lat": 30.59, "lon": 114.30, "tipo": "cuenca"},
    {"id": "pereira-co", "ciudad": "Pereira", "pais": "Colombia", "iso3": "COL", "region": "LatAm", "lat": 4.81, "lon": -75.69, "tipo": "ciudad"},
    {"id": "florianopolis-br", "ciudad": "Florianópolis", "pais": "Brasil", "iso3": "BRA", "region": "LatAm", "lat": -27.59, "lon": -48.55, "tipo": "ciudad"},
    {"id": "sevilla-es", "ciudad": "Sevilla", "pais": "España", "iso3": "ESP", "region": "Mundo", "lat": 37.39, "lon": -5.99, "tipo": "ciudad"},
    {"id": "milan-it", "ciudad": "Milán", "pais": "Italia", "iso3": "ITA", "region": "Mundo", "lat": 45.46, "lon": 9.19, "tipo": "ciudad"},
]

LATITUDES = ",".join(str(p["lat"]) for p in PUNTOS)
LONGITUDES = ",".join(str(p["lon"]) for p in PUNTOS)


def por_region(region: str) -> list[dict]:
    return [p for p in PUNTOS if p["region"] == region]


def resumen() -> dict:
    return {
        "total": len(PUNTOS),
        "latam": len(por_region("LatAm")),
        "mundo": len(por_region("Mundo")),
    }
